src/java/c_bank/BankBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package c_bank;

import javax.faces.bean.ManagedBean;

@ManagedBean
public class BankBean {

    private static BankDAOInterface adatbazis = new BankDAOArrayList();
    private String ugyfelAzon;
    private BankUgyfel ugyfel;

    public String getUgyfelAzon() {
        return ugyfelAzon;
    }

    public void setUgyfelAzon(String ugyfelAzon) {
        this.ugyfelAzon = ugyfelAzon.trim();
    }

    public String egyenlegMutat() {
        ugyfel = adatbazis.ugyfelKeres(ugyfelAzon);
        if (ugyfel == null) {
            return "nincs";
        } else if (ugyfel.getEgyenleg() < 0) {
            return "fenyeget";
        } else {
            return "normal";
        }
    }

    public BankUgyfel getUgyfel() {
        return ugyfel;
    }
}

src/java/f_irsz/IrszBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package f_irsz;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;

/**
 *
 * @author nbalazs
 */
@ManagedBean
@SessionScoped
public class IrszBean implements Serializable {

    private int megyeAzon;
    private String varosIrsz;
    private boolean varosListaTiltva = false;
    private IrszAdatok adatok = new IrszAdatok();

    public boolean isVarosListaTiltva() {
        return varosListaTiltva;
    }

    public int getMegyeAzon() {
        return megyeAzon;
    }

    public void setMegyeAzon(int megyeAzon) {
        this.megyeAzon = megyeAzon;
        varosIrsz = "";
        varosListaTiltva = megyeAzon == 0;
    }

    public String getVarosIrsz() {
        return varosIrsz;
    }

    public void setVarosIrsz(String varosIrsz) {
        this.varosIrsz = varosIrsz;
    }

    public List<Megye> getMegyek() {
        return (adatok.getMegyek());
    }

    public List<Varos> getVarosok() {
        return (adatok.getVarosok(megyeAzon));
    }
}

web/Masik.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>
        Ez egy másik oldal már
    </h:body>
</html>

web/a_veletlen/alma.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <h:head>
        <title>Alma oldala</title>
    </h:head>
    <h:body>
        <center>
            <h1>Alma</h1>
            <h1>Apple</h1>
            <h1>Apfel</h1>
            <h1>Omena</h1>
        </center>
    </h:body>
</html>

web/a_veletlen/korte.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <h:head>
        <title>Körte oldala</title>
    </h:head>
    <h:body>
        <center>
            <h1>Körte</h1>
            <h1>Pear</h1>
            <h1>Birne</h1>
            <h1>Päärynä</h1>
        </center>
</h:body>
</html>

web/a_veletlen/oszibarack.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <h:head>
        <title>Őszibarack oldala</title>
    </h:head>
    <h:body>
        <center>
            <h1>Őszibarack</h1>
            <h1>Peach</h1>
            <h1>Pfirsich</h1>
            <h1>Persikka</h1>
        </center>
    </h:body>
</html>

web/a_veletlen/valaszto.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <h:head>
        <title>Válassz oldalt!</title>
    </h:head>
    <h:body>
        <center>
            <h:form>
                <h1>Nyomd meg a gombot az oldalválasztáshoz!</h1>
                <h:commandButton value="Ezt nyomd meg a választáshoz"
                                 action="#{navigacio.veletlenOldal()}"/>
            </h:form>
        </center>
    </h:body>
</html>

web/b_koszon/hogyHivnak.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <h:head>
        <title>Hogy hívnak?</title>
    </h:head>
    <h:body>
        <center>
            <h1>Hogy hívnak?</h1>
                <h:form>
                    <h:inputText value="#{koszones.nev}"/>
                    <h:commandButton value="Köszön"
                                     action="#{koszones.koszon()}"/>
                </h:form>
        </center>
    </h:body>
</html>

web/b_koszon/koszon.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>
        <center>
            <h1>Hello #{koszones.nev}!</h1>
        </center>
        
    </h:body>
</html>

web/b_koszon/nincsKitoltve.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>
        <center>
            <h1>Nem adott meg nevet! (<a href="hogyHivnak.xhtml">Próbáljuk újra!</a>)</h1>
        </center>
    </h:body>
</html>

web/c_bank/belep.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <h:head>
        <title>Bank Bank</title>
    </h:head>
    <h:body>
        <center>
            <h1>Üdvözlet a Bank Bankban!</h1>
            <h:form>
                Azonosító: 
                <h:inputText value="#{bankBean.ugyfelAzon}"/>
                <h:commandButton value="Mutat"
                                 action="#{bankBean.egyenlegMutat()}"/>
            </h:form>
        </center>
    </h:body>
</html>

web/c_bank/fenyeget.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <h:head>
        <title>Fenyegetés</title>
    </h:head>
    <h:body>
        <center>
            <h1>Fenyegetés</h1>
            <h3>Kedves #{bankBean.ugyfel.nev}! Fizess vissza azonnal #{-bankBean.ugyfel.egyenleg} Forintot!</h3>
        </center>
    </h:body>
</html>

web/c_bank/nincs.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <h:head>
        <title>Nincs ilyen ügyfél</title>
    </h:head>
    <h:body>
        <center>
            <h3>Sajnáljuk, #{bankBean.ugyfelAzon} azonosítójú ügyfél nincs a rendszerben!</h3>
            <a href="belep.xhtml">Vissazlép a bejelentkező oldalra</a>
        </center>
    </h:body>
</html>

web/c_bank/normal.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <h:head>
        <title>#{bankBean.ugyfel.nev} adatai</title>
    </h:head>
    <h:body>
        <center>
            <h1>Adatok</h1>
            <table>
                <tr>
                    <td>Azonosító</td>
                    <td>#{bankBean.ugyfel.azon}</td>
                </tr>
                <tr>
                    <td>Név</td>
                    <td>#{bankBean.ugyfel.nev}</td>
                </tr>
                <tr>
                    <td>Egyenleg</td>
                    <td>#{bankBean.ugyfel.egyenleg}</td>
                </tr>
            </table>
        </center>
    </h:body>
</html>

web/d_valassz/mutat.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>
        <center>
            <h1>1. választás: <span style="color: #{valasztottSzin.szin1}">#{valasztottSzin.szin1}</span></h1>
            <h1>2. választás: <span style="color: #{valasztottSzin.szin2}">#{valasztottSzin.szin2}</span></h1>
            <h1>3. választás: <span style="color: #{valasztottSzin.szin3}">#{valasztottSzin.szin3}</span></h1>
            <h1>4. választás: <span style="color: #{valasztottSzin.szin4}">#{valasztottSzin.szin4}</span></h1>
        </center>
    </h:body>
</html>

web/d_valassz/valaszto.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>
        <center>        
            <h:form>
                <h1>Lenyíló lista</h1>
                <h:selectOneMenu value="#{valasztottSzin.szin1}">
                    <f:selectItems value="#{szinek.szinNevek}"/>
                </h:selectOneMenu>
                <hr/>
                <h1>Lista</h1>
                <h:selectOneListbox value="#{valasztottSzin.szin2}">
                    <f:selectItems value="#{szinek.szinErtekek}"/>
                </h:selectOneListbox>
                <hr/>
                <h1>Rádiógomb felsorolás</h1>
                <h:selectOneRadio value="#{valasztottSzin.szin3}">
                    <f:selectItems value="#{szinek.szinMap}"/>
                </h:selectOneRadio>
                <hr/>
                <h1>Lenyíló POJO listából</h1>
                <h:selectOneMenu value="#{valasztottSzin.szin4}">
                    <f:selectItems value="#{szinek.szinObjektumok}"
                                   var="szin"
                                   itemLabel="#{szin.nev}"
                                   itemValue="#{szin.ertek}"/>
                </h:selectOneMenu>
                <hr/>
                <h:commandButton value="Mutasd!" 
                                 action="#{valasztottSzin.szinMutatasa}"/>
            </h:form>
        </center>
    </h:body>
</html>

web/e_ajax/ido.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>Mennyi az idő?</title>
    </h:head>
    <h:body>
        <center>
            <h:form>
                <h1>Ajax nélküli megoldás</h1>
                <h:commandButton value="Megmondja az időt"
                                 action="#{idoGenerator.idotLeker}"/>
                <h3><h:outputText value="#{idoGenerator.ido}"/></h3>
                <hr/>
                <h1>Ajax megoldás</h1>
                <h:commandButton value="Megmondja az időt"
                                 action="#{idoGenerator.idotLeker}">
                    <f:ajax render="elsoEredmeny"/>
                </h:commandButton>
                <h3><h:outputText value="#{idoGenerator.ido}"
                                  id="elsoEredmeny"/></h3>
                <hr/>
                <h1>Ajax megoldás paraméterrel</h1>
                <h:inputText value="#{idoGenerator.formatum}"
                             id="formatumMezo"/>
                <h:commandButton value="Megmondja az időt"
                                 action="#{idoGenerator.idotLeker}">
                    <f:ajax execute="formatumMezo" 
                            render="masodikEredmeny"/>
                </h:commandButton>
                <h3><h:outputText value="#{idoGenerator.ido}"
                                  id="masodikEredmeny"/></h3>
                <hr/>
                
            </h:form>
        </center>

    </h:body>
</html>

web/f_irsz/valaszto.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>Irányítószám</title>
    </h:head>
    <h:body>
        <center>
            <h:form>
                <h1>Minek az irányítószáma kellene?</h1>
                Megye:
                <h:selectOneMenu value="#{irszBean.megyeAzon}">
                    <f:selectItem itemLabel="--Válassz megyét!--"/>
                    <f:selectItems value="#{irszBean.megyek}"
                                   var="megye"
                                   itemLabel="#{megye.nev}"
                                   itemValue="#{megye.azon}"/>
                    <f:ajax render="varosLista irsz"/>
                </h:selectOneMenu>
                <br/>
                Város:
                <h:selectOneMenu value="#{irszBean.varosIrsz}"
                                 disabled="#{irszBean.varosListaTiltva}"
                                 id="varosLista">
                    <f:selectItem itemLabel="--Válassz várost!--"/>
                    <f:selectItems value="#{irszBean.varosok}"
                                   var="varos"
                                   itemLabel="#{varos.nev}"
                                   itemValue="#{varos.irsz}"/>
                    <f:ajax render="irsz"/>
                </h:selectOneMenu>
                <br/>
                Irányítószám: 
                <strong>
                    <h:outputText value="#{irszBean.varosIrsz}"
                                  id ="irsz" />
                </strong>
            </h:form>
        </center>
    </h:body>
</html>

web/index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>
        <h:form>
            Nyomja meg a gombot, hogy a másik oldalra kerüljön
            <h:commandButton value="A másik oldal megnyitása" action="megnyit" ></h:commandButton>
        </h:form>
    </h:body>
</html>